force-app/main/default/objects/Data_Load_Request__c/Data_Load_Request__c.object-meta.xml
<CustomObject>
    <label>Data Load Request</label>
    <nameField>
        <displayFormat>DLR- {000000}</displayFormat>
        <label>Data Load Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Load_Request__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Data_Load_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Partial Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/Field_Mappings__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>Field Map-{00000000}</displayFormat>
        <label>Field Mappings No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Mappings__c/fields/Mapping_Included__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Included__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Mapping Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Object_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping__c</fullName>
    <label>Object Mapping</label>
    <referenceTo>Object_Mappings__c</referenceTo>
    <relationshipLabel>Field Mappings</relationshipLabel>
    <relationshipName>Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Target_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Label__c</fullName>
    <label>Target Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/Object_Mappings__c.object-meta.xml
<CustomObject>
    <label>Object Mappings</label>
    <nameField>
        <displayFormat>Obj Map -{000000}</displayFormat>
        <label>Object Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mappings__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delete Error</fullName>
            </value>
            <value>
                <fullName>Delete Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Sustain_UpdateCustomObjectRefBatch.cls
/***************************************************************************************************************
* Name - Sustain_UpdateCustomObjectRefBatch 
* Description - This class is used as Batch clas Processing the custom ref field on custom objects where managed package object reffered.
* Author - Accenture (Bindhyachal)
* Created Date - 9/10/2021
* Last Modified By & Date - Accenture, 9/10/2021
* ***************************************************************************************************************/

global class Sustain_UpdateCustomObjectRefBatch implements Database.Batchable<sObject>,  Database.Stateful, Database.AllowsCallouts {    
    Object_Mappings__c objMapping;
    String errorMessage='';
    List<Field_Mappings__c> fieldMaps;
    String dataLoadType = '';
    private static final string CurrentClassName = 'Sustain_UpdateCustomObjectRefBatch';

    public Sustain_UpdateCustomObjectRefBatch( Object_Mappings__c objMap, String dlType){       
        this.objMapping = objMap;
        this.dataLoadType = dlType;
    }
    
    // Start Method    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        fieldMaps = [Select Id,  Mapping_Included__c, Name, Object_Mapping__c,
                     Object_Mapping__r.Source_Object__c, Reference_To__c, Source_Field__c, Source_Field_Label__c, Source_Field_Type__c, Target_Field__c,
                     Target_Field_Label__c, Target_Field_Type__c  from Field_Mappings__c where Object_Mapping__c =:objMapping.Id AND Mapping_Included__c = true];
        String query = Sustain_UpdateCustomObjectRelationship.getSOQLString(fieldMaps);        
        return Database.getQueryLocator(query);
        
    }
    
    // Execute method
    global void execute(Database.BatchableContext BC, List<Sobject> scope) {
        string CurrentMethodName = 'execute';
        try {
            
            List<Sobject> recordsToBeUpdate = Sustain_UpdateCustomObjectRelationship.updateCustomObjectRecords(scope, fieldMaps);
            Database.update(recordsToBeUpdate, false);
        } catch(exception e) {
            errorMessage = e.getMessage();
            system.debug('Sustain_CreateMetadataBatch:error-->' + e);
            Sustain_UtilityError.createErrorLog(e, CurrentClassName, CurrentMethodName); 
            user us = [Select id,Name,email from User where id=:Userinfo.getUserId() limit 1];
            List<String> emailAddress = new List<String>();
            emailAddress.add(us.email);            
            Sustain_SendNotification sendData =new Sustain_SendNotification();
            sendData.sendEmailNotification('Sustain_Error_FinalDataLoadEmails',emailAddress);     
        }
    }
    
    // Finish Method
    global void finish(Database.BatchableContext BC) {
        string CurrentMethodName = 'finish';
        try{           
            if(String.isBlank(errorMessage)){                   
                objMapping.Status__c = 'Completed';
            }else{                    
                objMapping.Status__c = 'Error';   
            }
                  
            update objMapping;
            List<Object_Mappings__c> customObjectList = Sustain_UpdateCustomObjectRelationship.getCustomObjectMappingtoUpdate();
            if(customObjectList.size() >0){
                Sustain_UpdateCustomObjectRefBatch nextcustBatch = new Sustain_UpdateCustomObjectRefBatch(customObjectList[0], dataLoadType);
                database.executeBatch(nextcustBatch,(customObjectList[0].Batch_Size__c != null && customObjectList[0].Batch_Size__c.intValue() !=0) ? customObjectList[0].Batch_Size__c.intValue() : 200 );     
            }else{
                Data_Load_Request__c dataLoadReq = [Select id, Name, End_Date_Time__c,Status__c from Data_Load_Request__c order by CreatedDate DESC limit 1];
                System.debug('Error Message '+errorMessage);
                system.debug('end of batch');
                integer  totalRcrdCount = database.countQuery('SELECT count() FROM Object_Mappings__c where mapping_included__c=true');
                integer  processedRcrdCount = database.countQuery('SELECT count() FROM Object_Mappings__c where mapping_included__c=true and status__c =\'Completed\'');
                String emailTemplate = '';
                if(totalRcrdCount == processedRcrdCount) {
                    dataLoadReq.Status__c = 'Completed';
                    emailTemplate = 'Sustain_FinalDataLoadEmails';
                } else if(processedRcrdCount == 0) {
                    dataLoadReq.Status__c = 'Failed';
                    emailTemplate = 'Sustain_Error_FinalDataLoadEmails';
                } else {
                    dataLoadReq.Status__c = 'Partial Complete';
                    emailTemplate = 'Sustain_SampleDataLoadEmails';
                }
                dataLoadReq.End_Date_Time__c = System.now();
                try {
                    update dataLoadReq;
                } catch(exception e) {
                     system.debug('dataReq update error-->' + e);
                     Sustain_UtilityError.createErrorLog(e, CurrentClassName, CurrentMethodName); 
                }
                
                user us = [Select id,Name,email from User where id=:Userinfo.getUserId() limit 1];
                List<String> emailAddress = new List<String>();
                emailAddress.add(us.email);
                
                Sustain_SendNotification sendData =new Sustain_SendNotification();
                sendData.sendChatterNotification('MetadataEmails');
                if('FinalDataLoad'.equalsIgnoreCase(dataLoadType)){
                    sendData.sendEmailNotification(emailTemplate, emailAddress);
                    sendData.sendChatterNotification('FinalDataLoadEmails');
                }
            }
        }catch(Exception ex){
            Sustain_UtilityError.createErrorLog(ex, CurrentClassName, CurrentMethodName);     
            user us = [Select id,Name,email from User where id=:Userinfo.getUserId() limit 1];
            List<String> emailAddress = new List<String>();
            emailAddress.add(us.email);            
            Sustain_SendNotification sendData =new Sustain_SendNotification();
            sendData.sendEmailNotification('Sustain_Error_FinalDataLoadEmails',emailAddress);            
        } 
    }
}