force-app/main/default/objects/Data_Load_Request__c/Data_Load_Request__c.object-meta.xml
<CustomObject>
    <label>Data Load Request</label>
    <nameField>
        <displayFormat>DLR- {000000}</displayFormat>
        <label>Data Load Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Migration_Status__c/Migration_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Migration Status</label>
</CustomObject>

force-app/main/default/objects/Object_Mappings__c/Object_Mappings__c.object-meta.xml
<CustomObject>
    <label>Object Mappings</label>
    <nameField>
        <displayFormat>Obj Map -{000000}</displayFormat>
        <label>Object Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mappings__c/fields/Source_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Type__c</fullName>
    <label>Source Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sustain_app__Asset__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error Occurred</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Partial Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Sustain_DeleteSampleLoadBatchTest.cls
/***************************************************************************************************************
* Name - Sustain_DeleteSampleLoadBatchTest
* Description - This class is used as a test class for Sustain_DeleteSampleLoadBatch apex class.
* Author - Accenture (Bindhyachal)
* Created Date -9/19/2021
* Last Modified By & Date - Accenture, 2/16/2022
* ***************************************************************************************************************/
@isTest(SeeAllData=False)
private class Sustain_DeleteSampleLoadBatchTest {
    @testSetup
    static void setup() {
        sustain_app__Asset__c asset=Sustain_TestDataFactory.createAsset();      
        asset.Name='test';
        asset.Target_SFDC_ID__c = null;
        asset.Migration_Status__c = 'Not Started';
        insert asset; 
        
        Object_Mappings__c obj = Sustain_TestDataFactory.createObjectMapping();
        insert obj;
        obj.Source_Object__c= 'sustain_app__Asset__c';
        update obj;
        
        Data_Load_Request__c dataRec = Sustain_TestDataFactory.createDataLoadRequest();
        insert dataRec;
    }    
    
    @isTest static void testDelete() {
        User u1 = Sustain_TestDataFactory.createAdmninUser();
        System.runAs(u1){
            Test.startTest();
                Object_Mappings__c obj = [Select Id,Source_Object__c,Source_Record_Type__c from Object_Mappings__c limit 1];
                Data_Load_Request__c dataRec  = [select id from Data_Load_Request__c limit 1];            
            Test.stopTest();
        }
        sustain_app__Asset__c asset  = [select Id from  sustain_app__Asset__c limit 1];
        system.assertNotEquals(true, asset == null);
        
    }
}