force-app/main/default/objects/Field_Mappings__c/Field_Mappings__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>Field Map-{00000000}</displayFormat>
        <label>Field Mappings No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Mappings__c/fields/Calculated__c.field-meta.xml
<CustomField>
    <fullName>Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Calculated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Custom_Field__c.field-meta.xml
<CustomField>
    <fullName>Custom_Field__c</fullName>
    <formula>IF(Source_Field__c = &apos;Vendor_Name__c&apos;, FALSE, 
IF(
AND(
!BEGINS(Source_Field__c,&apos;sustain_app__&apos;),
OR(
CONTAINS(RIGHT(Source_Field__c,3) ,&apos;__c&apos;),
CONTAINS(RIGHT(Source_Field__c,3) ,&apos;__s&apos;)
)
),
TRUE, FALSE)
)</formula>
    <label>Custom Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Field_Created__c.field-meta.xml
<CustomField>
    <fullName>Field_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Field Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Mapping_Included__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Included__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Mapping Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/New_Field__c.field-meta.xml
<CustomField>
    <fullName>New_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Object_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping__c</fullName>
    <label>Object Mapping</label>
    <referenceTo>Object_Mappings__c</referenceTo>
    <relationshipLabel>Field Mappings</relationshipLabel>
    <relationshipName>Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Target_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Label__c</fullName>
    <label>Target Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/To_Review__c.field-meta.xml
<CustomField>
    <fullName>To_Review__c</fullName>
    <formula>AND(Custom_Field__c, NOT( Mapping_Included__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>To Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Migration_Status__c/Migration_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Migration Status</label>
</CustomObject>

force-app/main/default/objects/Migration_Status__c/fields/Metadata_Created__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Metadata Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Migration_Status__c/fields/Running_Metadata_Job__c.field-meta.xml
<CustomField>
    <fullName>Running_Metadata_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Running Metadata Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/Object_Mappings__c.object-meta.xml
<CustomObject>
    <label>Object Mappings</label>
    <nameField>
        <displayFormat>Obj Map -{000000}</displayFormat>
        <label>Object Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mappings__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sustain_app__Asset__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error Occurred</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Partial Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Sustain_CreateMetadataBatch.cls
/***************************************************************************************************************
* Name - Sustain_CreateMetadataBatch 
* Description - This class is used as Batch clas Processing the field mappings Records and create new fields.
* Author - Accenture (Bindhyachal)
* Created Date - 8/26/2021
* Last Modified By & Date - Accenture, 8/26/2021
* ***************************************************************************************************************/

global class Sustain_CreateMetadataBatch implements Database.Batchable<sObject>,Database.Stateful,Database.AllowsCallouts {
    
    // Start Method
    private static final string CurrentClassName = 'Sustain_CreateMetadataBatch';
    public static String errorMessage='';
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Set<String> staticFlds = Sustain_UtilConstants.STATICFIELDNAMES;
        String query = 'SELECT id,Name, Calculated__c, Comments__c, Source_Field__c,Target_Field_Label__c, Custom_Field__c, Mapping_Included__c, Object_Mapping__c, Object_Mapping__r.Source_Object__c, Object_Mapping__r.Object_Type__c, '+
            'Object_Mapping__r.Target_Object__c,Source_Field_Type__c, Target_Field__c, Reference_To__c, Target_Field_Type__c, To_Review__c FROM Field_Mappings__c '+
            'where ((New_Field__c = true AND Object_Mapping__r.Mapping_Included__c = true AND Mapping_Included__c = true AND Calculated__c = false) OR Source_Field__c IN:staticFlds ) AND Field_Created__c = false order By Object_Mapping__r.Source_Object__c ASC';
        System.debug('query--------------> ' + query);
        return Database.getQueryLocator(query);        
    }

    // Execute method
    global void execute(Database.BatchableContext BC, List<Field_Mappings__c> scope) {
        System.debug('Inside execute--------------> ');
        string CurrentMethodName = 'execute';
        Set<String> fieldsName = new Set<String>();
        Set<String> objectsName = new Set<String>();
        Set<String> trgtObject = new Set<String>();
        List<Object_Mappings__c> staticFieldMappingsObj = new List<Object_Mappings__c>();
        List<Field_Mappings__c> fieldMappingsObj = new List<Field_Mappings__c>();
        Set<String> staticFieldObj = new Set<String>();
        Map<String, List<Field_Mappings__c>> refFieldOnSourceMap = new Map<String, List<Field_Mappings__c>>();       
        
        try {
            Set<String> createdFields = new Set<String>();
            String sql = 'SELECT id,Name,Object_Mapping__r.Target_Object__c,Target_Field__c, Field_Created__c FROM Field_Mappings__c '
             +' where Field_Created__c = true and id in:scope order By Object_Mapping__r.Source_Object__c ASC';
            for(Field_Mappings__c fl: database.query(sql)){
                createdFields.add(fl.Object_Mapping__r.Target_Object__c+ '.' + fl.Target_Field__c);
            } 
            Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
            List<String> apiNames = new List<String>();
            String uniqueKey = '';
            if(Sustain_UtilConstants.STATICFIELDNAMES.contains(scope[0].Source_Field__c) && scope[0].Source_Field__c != 'Source_Record_ID__c'){
                apiNames.add(scope[0].Object_Mapping__r.source_Object__c);
                uniqueKey = scope[0].Object_Mapping__r.source_Object__c.replace(Label.Sustain_Name_Space_Prefix, '') + '.' + scope[0].Target_Field__c.replace(Label.Sustain_Name_Space_Prefix, '');
            } else {
                apiNames.add(scope[0].Object_Mapping__r.Target_Object__c);
                uniqueKey = scope[0].Object_Mapping__r.Target_Object__c.replace(Label.Sustain_Name_Space_Prefix, '') + '.' + scope[0].Target_Field__c.replace(Label.Sustain_Name_Space_Prefix, '');
            }
            Schema.DescribeSObjectResult[] results = Schema.describeSObjects(apiNames);
            for(Schema.DescribeSobjectResult describeResult : results){
                System.debug('describeResult '+describeResult.getLabel());
                for(Schema.SobjectField field: describeResult.fields.getMap().values()){
                    if(describeResult.getName().replace(Label.Sustain_Name_Space_Prefix, '')+'.'+field.getDescribe().getName().replace(Label.Sustain_Name_Space_Prefix, '') == uniqueKey){
                        createdFields.add(describeResult.getName().replace(Label.Sustain_Name_Space_Prefix, '')+'.'+field.getDescribe().getName().replace(Label.Sustain_Name_Space_Prefix, ''));
                        break;
                    }
                    system.debug('fields--->' + describeResult.getName()+'.'+field.getDescribe().getName());
                }
            }

            system.debug('scope-->' + scope.size());

            for(Field_Mappings__c fmapping : scope){                
                if(!createdFields.contains(fmapping.Object_Mapping__r.Target_Object__c+ '.' + fmapping.Target_Field__c) 
                 && !createdFields.contains(fmapping.Object_Mapping__r.source_Object__c+ '.' + fmapping.Target_Field__c)){
                    if(!Sustain_UtilConstants.STATICFIELDNAMES.contains(fmapping.Source_Field__c) && fmapping.Object_Mapping__r.Object_Type__c != 'custom'){
                       fieldsName.add(fmapping.Source_Field__c.replace(Label.Sustain_Name_Space_Prefix, ''));                
                        system.debug('fmapping.Source_Field__c-->' + fmapping.Source_Field__c);  
                        objectsName.add(fmapping.Object_Mapping__r.Source_Object__c); 
                        trgtObject.add(fmapping.Object_Mapping__r.Target_Object__c); 
                        system.debug('objectsName-->' + objectsName);
                        system.debug('trgtObject-->' + trgtObject);
                        Sustain_MigrateCustomFieldsController.readCustomObjectSync(new list<String>(objectsName	), (new list<string>(trgtObject))[0], fieldsName, null);  
                    } else if(fmapping.Object_Mapping__r.Object_Type__c == 'custom' ){
                        List<Field_Mappings__c> fieldMapList = new List<Field_Mappings__c>();
                        System.debug('refFieldOnSourceMap '+refFieldOnSourceMap);
                        String key = fmapping.Object_Mapping__r.Source_Object__c+'.'+fmapping.Source_Field__c;
                        System.debug('inside key '+Key);
                        if(refFieldOnSourceMap != null && 
                            refFieldOnSourceMap.containsKey(key)){
                            System.debug('refFieldOnSourceMap.get(fmapping.Source_Field__c+fmapping.Object_Mapping__c) '+refFieldOnSourceMap.get(key));
                            fieldMapList = refFieldOnSourceMap.get(key);
                        }
                        System.debug('fieldMapList '+fieldMapList);
                        fieldMapList.add(fmapping);
                        refFieldOnSourceMap.put(key, fieldMapList);
                    } else{
                        System.debug('staticFieldObj '+staticFieldObj);
                        if(!staticFieldObj.contains(fmapping.Object_Mapping__c)){
                            staticFieldMappingsObj.add(fmapping.Object_Mapping__r);
                            fieldsName.add(fmapping.Source_Field__c); 
                            staticFieldObj.add(fmapping.Object_Mapping__c);
                        }
                    }
                }  else {
                    fmapping.Field_Created__c = true;
                    fieldMappingsObj.add(fmapping);
                }             
            }
            system.debug('scope.size()-->' + scope.size());
            if(refFieldOnSourceMap.size() > 0){                
                Sustain_MigrateCustomFieldsController.processFieldMappings(refFieldOnSourceMap);
            }
            if(staticFieldMappingsObj.size() > 0){
                for(Object_Mappings__c objMap : staticFieldMappingsObj){
                    if(fieldsName.contains('Source_Record_ID__c')){
                        Sustain_MigrateCustomFieldsController.readCustomObjectSync(new list<String> {'StnryAssetEnvrSrc'}, objMap.Target_Object__c, fieldsName, null);    
                    }else{
                        Sustain_MigrateCustomFieldsController.readCustomObjectSync(new list<String> {'Sustain_app__Asset__c'}, objMap.Source_Object__c, fieldsName, null);  
                    }
                }
            }  
            Database.update(fieldMappingsObj, false);    
        } catch(exception e) {
            errorMessage = e.getMessage();
            system.debug('Sustain_CreateMetadataBatch:error-->' + e);
            Sustain_UtilityError.createErrorLog(e, CurrentClassName, CurrentMethodName);   
        }
    }
    
    // Finish Method
    global void finish(Database.BatchableContext BC) {
        string CurrentMethodName = 'finish';
        try{ 
            System.debug('errorMessage --->'+errorMessage);    
            user us = [Select id,Name,email from User where id=:Userinfo.getUserId() limit 1];
            List<String> emailAddress = new List<String>();
            emailAddress.add(us.email);
            Sustain_SendNotification sendData =new Sustain_SendNotification();
            if(String.isBlank(errorMessage)){               
                Migration_Status__c ms = Migration_Status__c.getOrgDefaults();                
                ms.Metadata_Created__c = true;
                ms.Running_Metadata_Job__c = false;
                update ms;  
                sendData.sendChatterNotification('MetadataEmails');
                sendData.sendEmailNotification('Sustain_MetadataEmails',emailAddress);  
            }else{                   
                sendData.sendEmailNotification('Sustain_MetadataErrorEmails',emailAddress);  
            }
        }catch(Exception ex){
            Sustain_UtilityError.createErrorLog(ex, CurrentClassName, CurrentMethodName);            
        } 
    }
}