force-app/main/default/objects/Field_Mappings__c/Field_Mappings__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>Field Map-{00000000}</displayFormat>
        <label>Field Mappings No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Mappings__c/fields/Calculated__c.field-meta.xml
<CustomField>
    <fullName>Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Calculated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Mapping_Included__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Included__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Mapping Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/New_Field__c.field-meta.xml
<CustomField>
    <fullName>New_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Object_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping__c</fullName>
    <label>Object Mapping</label>
    <referenceTo>Object_Mappings__c</referenceTo>
    <relationshipLabel>Field Mappings</relationshipLabel>
    <relationshipName>Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Target_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Label__c</fullName>
    <label>Target Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Status__c/Migration_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Migration Status</label>
</CustomObject>

force-app/main/default/objects/Migration_Status__c/fields/Metadata_Created__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Metadata Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/Object_Mappings__c.object-meta.xml
<CustomObject>
    <label>Object Mappings</label>
    <nameField>
        <displayFormat>Obj Map -{000000}</displayFormat>
        <label>Object Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mappings__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence_Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Source_Object_Label__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Label__c</fullName>
    <label>Source Object Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Source_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Type__c</fullName>
    <label>Source Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delete Error</fullName>
            </value>
            <value>
                <fullName>Delete Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Target_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Type__c</fullName>
    <label>Target Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Sustain_FieldMappingTriggerTest.cls
@isTest(SeeAllData=False)
private class Sustain_FieldMappingTriggerTest {
    // private Sustain_FieldMappingTriggerTest(){
    //  system.debug('Constructor');
    // }
    
    @isTest static void unitTest() {
        //Sustain_FieldMappingTriggerHandler fm=new Sustain_FieldMappingTriggerHandler();
        // List<Field_Mappings__c> fieldMappingList=[SELECT Id, Source_Field__c,Source_Field_Label__c,Source_Field_Type__c,Target_Field_Label__c,Target_Field__c, Target_Field_Type__c, Calculated__c, New_Field__c,Mapping_Included__c, Object_Mapping__c from Field_Mappings__c]; 
        
        Map<Id,Field_Mappings__c> oldmap=new Map<Id,Field_Mappings__c> ();
        
        Object_Mappings__c obj = new Object_Mappings__c();
        obj.Source_Object__c= 'Test__c';
        obj.Target_Object__c = 'GeneratedWaste';
        obj.Source_Object_Label__c = 'Test';
        obj.Mapping_Included__c = true;
        obj.Source_Record_Type__c='reference';
        obj.Target_Record_Type__c='string';
        obj.Sequence_Number__c=4;
        obj.Status__c='Completed';
        insert obj;
        
        Field_Mappings__c objF = new Field_Mappings__c();
        List<Field_Mappings__c> fieldMappingList=new  List<Field_Mappings__c>();
        fieldMappingList.add(objF);
        objF.Mapping_Included__c= true;
        objF.New_Field__c = false;
        objF.Calculated__c = false;
        objF.Source_Field__c = 'test_datetime__c';
        objF.Source_Field_Type__c = 'DateTime';
        objF.Source_Field_Label__c = 'test datetime';
        objF.Required__c = true;
        objF.object_mapping__c = obj.id;
        insert objF;
        fieldMappingList.add(objF);
        oldmap.put(objF.id, objF);
        objF.Target_Field_Label__c = objF.Source_Field_Label__c;
        objF.Target_Field__c = objF.Source_Field__c;
        objF.Target_Field_Type__c = objF.Source_Field_Type__c;
        update objF;
        Migration_Status__c mg=new Migration_Status__c();
        mg.Metadata_Created__c=false;
        insert mg;
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u1 = new User(Alias = 'newUser', Email='aforce@aforceorg.com',
                           EmailEncodingKey='UTF-8', LastName='aforce', LanguageLocaleKey='en_US',
                           LocaleSidKey='en_US', ProfileId = p.Id,
                           TimeZoneSidKey='America/Los_Angeles', UserName='aforce@aforceorg.com');
        //Database.insert(u1);
        System.runAs(u1){
            Test.startTest();
            //Sustain_FieldMappingTriggerHandler.updateMigrationStatus(fieldMappingList,oldmap);
            //Sustain_FieldMappingTriggerHandler.updateMigrationStatus(null,null);
            objF.New_Field__c = true;
            update objF;
            Test.stopTest();
        }
        system.assertEquals(false, Migration_Status__c.getOrgDefaults().Metadata_Created__c);
        
    }
}