force-app/main/default/objects/Field_Mappings__c/Field_Mappings__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>Field Map-{00000000}</displayFormat>
        <label>Field Mappings No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Mappings__c/fields/New_Field__c.field-meta.xml
<CustomField>
    <fullName>New_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mappings__c/fields/Target_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Label__c</fullName>
    <label>Target Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Status__c/Migration_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Migration Status</label>
</CustomObject>

force-app/main/default/objects/Migration_Status__c/fields/Metadata_Created__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Metadata Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Sustain_FieldMappingTriggerHandler.cls
public without sharing class Sustain_FieldMappingTriggerHandler {
    private static final string CurrentClassName = 'Sustain_FieldMappingTriggerHandler';
    public static void updateMigrationStatus(List<Field_Mappings__c> fieldMappingList, Map<Id,Field_Mappings__c> oldMap){
        string CurrentMethodName = 'updateMigrationStatus';
        try{
        boolean temp = false;
        for(Field_Mappings__c fm : fieldMappingList ) {
            system.debug('fm.New_Field__c'+fm.New_Field__c);
            if(oldMap != null && fm.New_Field__c != oldMap.get(fm.Id).New_Field__c && fm.New_Field__c == true ){
                fm.Target_Field_Label__c = fm.Source_Field_Label__c;
                fm.Target_Field__c = fm.Source_Field__c;
                fm.Target_Field_Type__c = fm.Source_Field_Type__c;
                temp = true;
                //break;
            }
        } 
            system.debug('temp-->'+temp);
        if(temp == true){
            Migration_Status__c mig = Migration_Status__c.getOrgDefaults();
            mig.Metadata_Created__c = false;
            update mig;
        }
        }catch(Exception e){
            Sustain_UtilityError.createErrorLog(e, CurrentClassName, CurrentMethodName);
        }
    }
}