force-app/main/default/objects/Field_Mappings__c/Field_Mappings__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>Field Map-{00000000}</displayFormat>
        <label>Field Mappings No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Mappings__c/fields/Object_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping__c</fullName>
    <label>Object Mapping</label>
    <referenceTo>Object_Mappings__c</referenceTo>
    <relationshipLabel>Field Mappings</relationshipLabel>
    <relationshipName>Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/Object_Mappings__c.object-meta.xml
<CustomObject>
    <label>Object Mappings</label>
    <nameField>
        <displayFormat>Obj Map -{000000}</displayFormat>
        <label>Object Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Sustain_UpdateCustomObjectRelationTest.cls
/***************************************************************************************************************
* Name - Sustain_UpdateCustomObjectRelationTest
* Description - This class is used as a test class for Sustain_UpdateCustomObjectRelation apex class.
* Author - Accenture (Prateeka)
* Created Date -9/21/2021
* Last Modified By & Date - Accenture, 2/16/2022
* ***************************************************************************************************************/
@isTest(SeeAllData=False)
private class Sustain_UpdateCustomObjectRelationTest {
    static testmethod void setup() {
        Object_Mappings__c obj = Sustain_TestDataFactory.createObjectMapping();
        insert obj;
        List<Object_Mappings__c> mappingList =new List<Object_Mappings__c>();
        mappingList.add(obj);
        
        Field_Mappings__c objF = Sustain_TestDataFactory.createFieldMapping();
        objF.object_mapping__c = obj.id;
        insert objF;
        List<Field_Mappings__c> fieldMappingList =new List<Field_Mappings__c>();
        fieldMappingList.add(objF);
        Sustain_UpdateCustomObjectRelationship up=new Sustain_UpdateCustomObjectRelationship();
        List<sObject> listWRecords = new List<sObject>();
        User u1 = Sustain_TestDataFactory.createAdmninUser();       
        System.runAs(u1){
            String testStr = '';
            String testStr1 = '';
            test.startTest();
                testStr= Sustain_UpdateCustomObjectRelationship.getSOQLString(fieldMappingList);
                testStr1= Sustain_UpdateCustomObjectRelationship.getSOQLString(null);
                Sustain_UpdateCustomObjectRelationship.getCustomObjectMappingtoUpdate();
                Sustain_UpdateCustomObjectRelationship.updateCustomObjectRecords(listWRecords, fieldMappingList);
                Sustain_UpdateCustomObjectRelationship.updateCustomObjectRecords(null, null);
            test.stoptest();
            system.assertEquals(true, String.isNotBlank(testStr));
            system.assertEquals(false, String.isNotBlank(testStr1));
        }      
    }   
}