force-app/main/default/objects/Migration_Status__c/Migration_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Migration Status</label>
</CustomObject>

force-app/main/default/objects/Migration_Status__c/fields/Current_Migration_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Migration_Stage__c</fullName>
    <label>Current Migration Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Status__c/fields/Metadata_Created__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Metadata Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Migration_Status__c/fields/Ready_to_Launch__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Launch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to Launch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Migration_Status__c/fields/VendorRecordStatus__c.field-meta.xml
<CustomField>
    <fullName>VendorRecordStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VendorRecordStatus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/Object_Mappings__c.object-meta.xml
<CustomObject>
    <label>Object Mappings</label>
    <nameField>
        <displayFormat>Obj Map -{000000}</displayFormat>
        <label>Object Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mappings__c/fields/Source_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Type__c</fullName>
    <label>Source Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mappings__c/fields/Total_Records__c.field-meta.xml
<CustomField>
    <fullName>Total_Records__c</fullName>
    <label>Total Records</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sustain_app__ServiceProvider__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error Occurred</fullName>
            </value>
            <value>
                <fullName>Partial Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <displayFormat>VENDOR-{0000000}</displayFormat>
        <label>Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error Occurred</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <label>Vendor Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/Sustain_CreateVendorRecordBatch.cls
/**
 * @description       : 
 * @author            : Accenture
 * @group             : 
 * @last modified on  : 02-01-2022
 * @last modified by  : Accenture
**/
global class Sustain_CreateVendorRecordBatch implements Database.Batchable<sObject>,Database.Stateful {

    public Set<String> euRecordTypes = new Set<String>();
    public Integer currentEURecordTypeNo; 
    public List<String> userEmails; 
    public String orgIDS; 
    public Boolean noErrorExist = true;
    public static final string CurrentClassName = 'Sustain_CreateVendorRecordBatch';   
    
    public Sustain_CreateVendorRecordBatch(Integer energyUseRecordTypeNo, List<String> userEmails, String orgIDS){
        this.currentEURecordTypeNo = energyUseRecordTypeNo;  
        this.userEmails = userEmails;
        this.orgIDS = orgIDS;       
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {               
        String currentEURecordType = Sustain_UtilConstants.EURecordTypesMap.get(currentEURecordTypeNo);
        String query = 'SELECT id,Name,RecordType.Name,sustain_app__VendorName__c from sustain_app__EnergyConsumption__c where sustain_app__VendorName__c != null AND RecordType.DeveloperName =:currentEURecordType';
        return Database.getQueryLocator(query);
    }
    
    // Execute method
    global void execute(Database.BatchableContext BC, List<sustain_app__EnergyConsumption__c> scope) {
        string CurrentMethodName = 'execute';
        try{
            
            List<Vendor__c> insertResultLst = new List<Vendor__c>();
            
            system.debug('value of scope>>>'+scope);
            
            Set<String> VendorSet = new Set<String>();
            Set<String> vendorNames = new Set<String>();
            
            for(sustain_app__EnergyConsumption__c eurData : scope){
                system.debug('value of eurData.RecordTypeName >>'+eurData.RecordType.Name);
                system.debug('value of eurData.sustain_app__VendorName__c >>'+eurData.sustain_app__VendorName__c);
                VendorSet.add(eurData.sustain_app__VendorName__c);                
            }
            system.debug('value of vendor set >>>>>>>'+VendorSet);                
            
            for(Vendor__c ven: [select Id, Name, Vendor_Name__c from Vendor__c where Vendor_Name__c IN: vendorSet ]){
                vendorNames.add(ven.Vendor_Name__c);
            }
            
            for(sustain_app__ServiceProvider__c sup: [select Id, Name from sustain_app__ServiceProvider__c where Name IN: vendorSet ]){
                vendorNames.add(sup.Name);
            }
                        
            for(String venName: VendorSet){
                if(!vendorNames.contains(venName)){
                    Vendor__c vendor = new Vendor__c();
                    vendor.Vendor_Name__c = venName;
                    insertResultLst.add(vendor);
                    system.debug('value of vendor rec>>>>>>>'+insertResultLst);
                }
            }
            
            if(!insertResultLst.isEmpty()){
                database.insert(insertResultLst);
            }
            
        }catch(Exception e){
            System.debug('An exception occurred: ' + e.getMessage());
            Sustain_UtilityError.createErrorLog(e, CurrentClassName, CurrentMethodName); 
            noErrorExist = false;
        }
    }
    
    global void finish(Database.BatchableContext BC) {        
        System.debug('currentEURecordTypeNo '+currentEURecordTypeNo);
        string CurrentMethodName = 'finish';
        try{
            if(Sustain_UtilConstants.EURecordTypesMap.containsKey(currentEURecordTypeNo+1)){
                Sustain_CreateVendorRecordBatch nextcustBatch = new Sustain_CreateVendorRecordBatch(currentEURecordTypeNo+1, userEmails, orgIDS);
                database.executeBatch(nextcustBatch, 1000);
            } else{
                List<Object_Mappings__c> objMaptobeUpdate = new List<Object_Mappings__c>();
                // Get those records based on the IDs
                for(Object_Mappings__c oMap:[select id,Source_Record_Type__c,Source_Object__c,Target_Object__c from Object_Mappings__c where Source_Object__c = 'Vendor__c']){
                    // Process records   
                    String QueryString = 'SELECT count() FROM '+oMap.Source_Object__c;
                    if(oMap.Source_Record_Type__c != null && oMap.Source_Record_Type__c != 'Master'){
                        QueryString = QueryString + ' where recordType.DeveloperName = \''+ oMap.Source_Record_Type__c + '\''; 
                    } 
                    oMap.Total_Records__c = String.valueOf(Database.countQuery(QueryString));
                    System.debug(' temp.Total_Records__c'+ oMap.Total_Records__c);                                 
                    objMaptobeUpdate.add(oMap);             
                }
        
                if(objMaptobeUpdate.size() > 0){
                    update objMaptobeUpdate;
                }            
            
                Migration_Status__c ms = Migration_Status__c.getInstance(orgIDs);
                if(ms==null){
                    ms = new Migration_Status__c();                              
                }
                ms.Current_Migration_Stage__c   = 'Org Data Scan Output'; 
                ms.Ready_To_Launch__c = false;
                ms.MetaData_Created__c = false;
                ms.VendorRecordStatus__c = noErrorExist;
                upsert ms;
                
                Sustain_SendNotification sendData =new Sustain_SendNotification();
                sendData.sendEmailNotification('Sustain_VendorRecordsEmail',userEmails);
            }
        }catch(Exception e){
            System.debug('An exception occurred: ' + e.getMessage());
            Sustain_UtilityError.createErrorLog(e, CurrentClassName, CurrentMethodName); 
            noErrorExist = false;
            Sustain_SendNotification sendData =new Sustain_SendNotification();
            sendData.sendEmailNotification('Sustain_VendorRecordsErrorEmail',userEmails);
        }
    }
}